import type { GeneratedResumeHistoryItem } from "@/lib/generated-resume-types"

export const mockGeneratedResumeHistory: GeneratedResumeHistoryItem[] = [
  {
    id: "resume_hist_001",
    sessionId: "sess_hist_001",
    title: "Currículo ATS - Designer de Produto",
    mode: "ats_enhancement",
    status: "completed",
    createdAt: "2026-04-24T13:10:00.000Z",
    updatedAt: "2026-04-24T13:18:00.000Z",
    targetRole: "Designer de Produto Sênior",
    targetJobSnippet: "Resumo e experiências reescritos para ATS com foco em sistemas de design, discovery e métricas de produto.",
    pdfAvailable: true,
  },
  {
    id: "resume_hist_002",
    sessionId: "sess_hist_002",
    title: "Currículo alvo - Liderança de Produto",
    mode: "job_targeting",
    status: "completed",
    createdAt: "2026-04-23T15:30:00.000Z",
    updatedAt: "2026-04-23T15:36:00.000Z",
    targetRole: "Líder de Produto",
    targetJobSnippet: "Versão direcionada para liderança de produto, estratégia, OKRs, discovery contínuo e gestão de times.",
    pdfAvailable: true,
  },
  {
    id: "resume_hist_003",
    sessionId: "sess_hist_003",
    title: "Currículo ATS - Sucesso do Cliente",
    mode: "ats_enhancement",
    status: "processing",
    createdAt: "2026-04-23T11:05:00.000Z",
    targetRole: "Gerente de Sucesso do Cliente",
    targetJobSnippet: "Nova geração em andamento com foco em retenção, onboarding e expansão de carteira.",
    pdfAvailable: false,
  },
  {
    id: "resume_hist_004",
    sessionId: "sess_hist_004",
    title: "Currículo alvo - Operações de Receita",
    mode: "job_targeting",
    status: "failed",
    createdAt: "2026-04-22T18:22:00.000Z",
    targetRole: "Analista de Operações de Receita",
    targetJobSnippet: "Tentativa anterior com direcionamento para operações, CRM, forecast e automações comerciais.",
    pdfAvailable: false,
  },
  {
    id: "resume_hist_005",
    sessionId: "sess_hist_005",
    title: "Currículo ATS - Redação UX",
    mode: "ats_enhancement",
    status: "completed",
    createdAt: "2026-04-21T10:45:00.000Z",
    updatedAt: "2026-04-21T10:49:00.000Z",
    targetRole: "Redator UX",
    targetJobSnippet: "Versão enxuta para ATS destacando estratégia de conteúdo, escrita para UX e experimentação.",
    pdfAvailable: true,
  },
  {
    id: "resume_hist_006",
    sessionId: "sess_hist_006",
    title: "Currículo alvo - Engenharia de Analytics",
    mode: "job_targeting",
    status: "completed",
    createdAt: "2026-04-20T08:15:00.000Z",
    updatedAt: "2026-04-20T08:21:00.000Z",
    targetRole: "Engenheiro de Analytics",
    targetJobSnippet: "Currículo adaptado para dbt, modelagem analítica, qualidade de dados e parceria com produto.",
    pdfAvailable: true,
  },
]
