import type { LocalizationResource } from "@clerk/types"

export const embeddedClerkLocalizationPtBr: LocalizationResource = {
  locale: "pt-BR",
  socialButtonsBlockButton: "Continuar com {{provider|titleize}}",
  socialButtonsBlockButtonManyInView: "Continuar com",
  dividerText: "OU",
  formButtonPrimary: "Continuar",
  formButtonPrimary__verify: "Verificar",
  formFieldLabel__emailAddress: "E-mail",
  formFieldLabel__emailAddress_username: "E-mail",
  formFieldLabel__password: "Senha",
  formFieldLabel__firstName: "Primeiro nome",
  formFieldLabel__lastName: "Sobrenome",
  formFieldInputPlaceholder__emailAddress: "Digite seu e-mail",
  formFieldInputPlaceholder__emailAddress_username: "Digite seu e-mail",
  formFieldInputPlaceholder__password: "Digite sua senha",
  formFieldInputPlaceholder__firstName: "Primeiro nome",
  formFieldInputPlaceholder__lastName: "Sobrenome",
  formFieldAction__forgotPassword: "Esqueceu sua senha?",
  formFieldHintText__optional: "",
  signInEnterPasswordTitle: "Digite sua senha",
  backButton: "Voltar",
  footerActionLink__useAnotherMethod: "Usar outro método",
  signIn: {
    start: {
      title: "Entrar na sua conta",
      subtitle: "",
      actionText: "Não tem conta?",
      actionLink: "Criar conta",
      actionLink__use_email: "Usar e-mail",
      actionLink__use_phone: "Usar telefone",
      actionLink__use_username: "Usar usuario",
      actionLink__use_email_username: "Usar e-mail",
      actionLink__use_passkey: "Usar passkey",
    },
    password: {
      title: "Digite sua senha",
      subtitle: "",
      actionLink: "Esqueceu sua senha?",
    },
    forgotPassword: {
      title: "Recuperar senha",
      subtitle: "",
      subtitle_email: "",
      subtitle_phone: "",
      formTitle: "Verifique seu e-mail",
      resendButton: "Reenviar código",
    },
    forgotPasswordAlternativeMethods: {
      title: "Escolha outra forma",
      label__alternativeMethods: "Outros métodos",
      blockButton__resetPassword: "Redefinir senha",
    },
    resetPassword: {
      title: "Redefinir senha",
      formButtonPrimary: "Salvar nova senha",
      successMessage: "Senha atualizada com sucesso.",
      requiredMessage: "Preencha este campo.",
    },
    emailCode: {
      title: "Verifique seu e-mail",
      subtitle: "",
      formTitle: "Digite o código",
      resendButton: "Reenviar código",
    },
    emailLink: {
      title: "Confira seu e-mail",
      subtitle: "",
      formTitle: "Link enviado",
      formSubtitle: "",
      resendButton: "Reenviar link",
      unusedTab: {
        title: "Link não utilizado",
      },
      verified: {
        title: "E-mail verificado",
        subtitle: "",
      },
      verifiedSwitchTab: {
        titleNewTab: "Abra o link enviado",
        subtitleNewTab: "",
      },
    },
  },
  signUp: {
    start: {
      title: "Criar conta",
      subtitle: "",
      actionText: "Já tem conta?",
      actionLink: "Entrar",
      actionLink__use_phone: "Usar telefone",
      actionLink__use_email: "Usar e-mail",
    },
    continue: {
      title: "Complete seu cadastro",
      subtitle: "",
      actionText: "Já tem conta?",
      actionLink: "Entrar",
    },
    emailLink: {
      title: "Confira seu e-mail",
      subtitle: "",
      formTitle: "Link enviado",
      formSubtitle: "",
      resendButton: "Reenviar link",
      verified: {
        title: "E-mail verificado",
      },
      loading: {
        title: "Verificando",
      },
      verifiedSwitchTab: {
        title: "Abra o link enviado",
        subtitle: "",
        subtitleNewTab: "",
      },
      clientMismatch: {
        title: "Verifique no mesmo navegador",
        subtitle: "",
      },
    },
    emailCode: {
      title: "Verifique seu e-mail",
      subtitle: "",
      formTitle: "Digite o código",
      formSubtitle: "",
      resendButton: "Reenviar código",
    },
  },
}
